resources:
  - name: gitResource12
    type: GitRepo
#     repoPath: bindushree16/test_c7java
    configuration:
      gitProvider: bindu_github
      path: bindushree16/test_c7java
      branches:
        only: master
    version:
      sha: master
      
pipelines:
  - name: pipelineQA
    steps:
      - name: test
        type: Bash
        configuration:
          inputResources:
            - name: gitResource12
        execution:
          onExecute:
            - printenv
            - pushd $res_gitResource12_resourcePath
            - docker build -t=test:dev .
      - name: test1
        type: Bash
        execution:
          onExecute:
#             - _set_jdk openjdk8
#             - java --version
#             - echo $JAVA_HOME
#             - echo $PATH
            - _set_jdk openjdk11
            - java --version
            - echo $JAVA_HOME
            - echo $PATH
        configuration:
          inputSteps:
            - name: test
          runtime:
            type: image
            image:
              custom:
                name: test
                tag: dev
                autoPull: false
