resources:
  - name: gitResource
    type: GitRepo
#     repoPath: bindushree16/test_c7java
    configuration:
      gitProvider: bindu_github
      path: bindushree16/test_c7java
      branches:
        only: master
      buildOn:
         commit: false  
    version:
      sha: master
      
pipelines:
  - name: pipeline
    steps:
      - name: test
        type: Bash
        configuration:
          nodePool: varsha_u16
          inputSteps:
            - name: test
          runtime:
            type: image
            image:
              auto:
                language: java
#               custom:
#                 name: drydock/u18java
#                 tag: master
#                 autoPull: true
#                 name: testc7
#                 tag: dev
#                 autoPull: false
        execution:
          onExecute:
            - echo "hi"
            - java -version
            - _set_jdk openjdk11
            - java -version
            - echo $JAVA_HOME
            - echo $PATH
            - ant -version
            - mvn --version 
            - gradle --version            
            - _set_jdk openjdk8
            - java -version
            - echo $JAVA_HOME
            - echo $PATH
            - ant -version
            - mvn --version 
            - gradle --version
            
      - name: go
        type: Bash
        configuration:
          nodePool: vijay_node           
          inputSteps:
            - name: test   
          runtime:
            type: image
            image:
              auto:
                language: go
#                 versions:            
#               custom:
#                 name: drydock/u18go
#                 tag: master
#                 autoPull: true
        execution:
          onExecute:
            - source /root/.gvm/scripts/gvm
            - gvm list
            - go version
            - gvm use 1.11.10 
            - go version
            - gvm use 1.12.5
            - go version                
      - name: cpp
        type: Bash
        configuration:
          nodePool: vijay_node           
          inputSteps:
            - name: go      
          runtime:
            type: image
            image:
              auto:
                language: c
#                 versions:            
#               custom:
#                 name: drydock/u18cpp
#                 tag: master
#                 autoPull: true
        execution:
          onExecute:
            - gcc --version
            - clang --version     
