resources:
  - name: gitResource1211
    type: GitRepo
#     repoPath: bindushree16/test_c7java
    configuration:
      gitProvider: bindu_github
      path: bindushree16/c7java
      branches:
        only: master
      buildOn:
         commit: false  
    version:
      sha: master
      
pipelines:
  - name: pipelineQA
    steps:
      - name: test
        type: Bash
        configuration:
          nodePool: bindu_test
          inputResources:
            - name: gitResource1211
        execution:
          onExecute:
            - printenv
            - pushd $res_gitResource1211_resourcePath
            - docker build -t=testc7:dev .

      - name: test1
        type: Bash
        configuration:
          nodePool: bindu_test
          inputSteps:
            - name: test
          runtime:
            type: image
            image:
              custom:
                name: testc7
                tag: dev
                autoPull: false
        execution:
          onExecute:
            - _set_jdk openjdk11
            - java -version
            - echo $JAVA_HOME
            - echo $PATH
            - ant -version
            - mvn --version 
            - gradle --version            
            - _set_jdk openjdk8
            - java --version
            - echo $JAVA_HOME
            - echo $PATH
            - ant -version
            - mvn --version 
            - gradle --version
