resources:
  - name: gitResource
    type: GitRepo
#     repoPath: bindushree16/test_c7java
    configuration:
      gitProvider: bindu_github
      path: bindushree16/test_c7java
      branches:
        only: master
      buildOn:
         commit: false  
    version:
      sha: master
      
pipelines:
  - name: pipeline
    steps:
      - name: test1
        type: Bash
        configuration:
          nodePool: bindu_testnode
          inputResources:
            - name: gitResource
          runtime:
            type: host
        execution:
          onExecute:
            - echo "hi"
            
      - name: test2
        type: Bash
        configuration:
          nodePool: bindu_testnode           
          inputSteps:
            - name: test1  
          runtime:
            type: image
            image:
              auto:
                language: java
        execution:
          onExecute:
            - echo "hi"
            
      - name: test3
        type: Bash
        configuration:
          nodePool: bindu_testnode           
          inputSteps:
            - name: test2      
          runtime:
            type: image
            image:
              auto:
                language: java
        execution:
          onExecute:
            - echo "hi"    
