resources:
  - name: gitResource1211
    type: GitRepo
#     repoPath: bindushree16/test_c7java
    configuration:
      gitProvider: bindu_github
      path: bindushree16/test_c7java
      branches:
        only: master
      buildOn:
         commit: false  
    version:
      sha: master
      
pipelines:
  - name: pipelineQA
    steps:
      - name: test
        type: Bash
        configuration:
          nodePool: bindu_test
          inputResources:
            - name: gitResource1211
        execution:
          onExecute:
            - printenv
#             - pushd $res_gitResource1211_resourcePath
#             - 
#             - docker build -t=test:dev .
            
      - name: test1
        type: Bash
        configuration:
          nodePool: bindu_test
          inputSteps:
            - name: test
          runtime:
            type: image
            image:
              custom:
                name: drydock/c7java
                tag: master
                autoPull: true
        execution:
          onExecute:
            - _set_jdk openjdk11
            - java -version
            - echo $JAVA_HOME
            - echo $PATH
            - ant -version
            - mvn --version 
            - gradle --version
            - update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-8-openjdk-amd64/bin/java 
            - update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac             
            - _set_jdk openjdk8
            - java --version
            - echo $JAVA_HOME
            - echo $PATH
            - ant -version
            - mvn --version 
            - gradle --version
